// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzDg-5vMbkWHQYn4F67_oR_kDzMr7VFOM',
    appId: '1:1030578583072:android:11b74c4ddb085e59beee45',
    messagingSenderId: '1030578583072',
    projectId: 'e-stock-45b4a',
    storageBucket: 'e-stock-45b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2pVwMq8C2U0jfsIsssE7CsaTArZ0zZFU',
    appId: '1:1030578583072:ios:826004c24a18eb1fbeee45',
    messagingSenderId: '1030578583072',
    projectId: 'e-stock-45b4a',
    storageBucket: 'e-stock-45b4a.firebasestorage.app',
    iosBundleId: 'com.example.eStock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtHqTx06nKBKQJG1NQT_s1L0RLlK50Apg',
    appId: '1:1030578583072:web:6bff010ec26de655beee45',
    messagingSenderId: '1030578583072',
    projectId: 'e-stock-45b4a',
    authDomain: 'e-stock-45b4a.firebaseapp.com',
    storageBucket: 'e-stock-45b4a.firebasestorage.app',
    measurementId: 'G-PGFPTV65C8',
  );
}
